
---
- name: Test S3
  hosts: localhost
  connection: local 

  tasks:
    - name: delete new bucket
      aws_s3:
        bucket: test-s3-bucket-htunn
        mode:  delete
        region: ap-southeast-1